#!/bin/bash
# OElite per-project database setup
#
# Creates a database, dedicated user, and grants for each OElite project on
# the shared MongoDB. Runs ONCE per machine (after shared stack is up).
# Idempotent: re-running has no effect if databases already exist.
#
# Connection: Uses the local mongos at localhost:27017.
# Auth:       Creates a root user on admin DB via localhost exception on first
#             run. Per-project users are then created with SCRAM credentials.
#
# Credentials are read from .env (gitignored, via env_file in compose):
#   MONGO_ROOT_USER (default: admin)
#   MONGO_ROOT_PASS (generated by ./scripts/generate-secrets.sh)

set -euo pipefail

MONGO_HOST="${OELITE_MONGO_HOST:-localhost}"
MONGO_PORT="${OELITE_MONGO_PORT:-27017}"
ADMIN_USER="${MONGO_ROOT_USER:-admin}"
ADMIN_PASS="${MONGO_ROOT_PASS:-}"

# OElite projects that need their own MongoDB database
# (Add new projects here as they onboard to the shared stack.)
PROJECTS=(
  "origin_auth:uranus/origin-auth"
  "apex:jupiter/apex"
  "obelisk:venus/obelisk"
  "synapse:mercury/synapse"
  "stela:uranus/stela"
  "hermes:uranus/hermes"
  "orion:uranus/orion"
  "kortex:helios/kortex"
  "oesterling:helios/oesterling"
  "helios_core:helios/core"
  "sip:venus/sip"
  "stela_runtime:venus/stela-runtime"
)

# Use admin DB to create the root user (via localhost exception) and project users
echo "============================================================"
echo "  OElite per-project MongoDB setup"
echo "============================================================"
echo ""

# ── Create root user on admin DB via localhost exception ─────────────────────
# On first run (no users exist), MongoDB allows localhost connections without auth.
# We create a root user so that subsequent connections can authenticate.
echo "[admin] Creating root user '$ADMIN_USER' (if missing)..."
MONGO_INITDB_ROOT_USER="$ADMIN_USER" MONGO_INITDB_ROOT_PASS="$ADMIN_PASS" mongosh --host "$MONGO_HOST" --port "$MONGO_PORT" --quiet --eval '
  var adminDB = db.getSiblingDB("admin");
  var exists = adminDB.getUser(process.env.MONGO_INITDB_ROOT_USER);
  if (exists) {
    print("  root user exists: " + process.env.MONGO_INITDB_ROOT_USER);
  } else {
    adminDB.createUser({
      user: process.env.MONGO_INITDB_ROOT_USER,
      pwd: process.env.MONGO_INITDB_ROOT_PASS,
      roles: [
        { role: "root",               db: "admin" },
        { role: "userAdminAnyDatabase", db: "admin" },
        { role: "clusterAdmin",       db: "admin" }
      ]
    });
    print("  root user created: " + process.env.MONGO_INITDB_ROOT_USER);
  }
'

# Use env vars to pass credentials to mongosh (avoids shell interpolation issues
# with special chars in auto-generated passwords). mongosh exposes them via
# process.env inside --eval JS.
mongosh_auth_base="--quiet --host $MONGO_HOST --port $MONGO_PORT --authenticationDatabase admin"

for entry in "${PROJECTS[@]}"; do
  db="${entry%%:*}"
  repo="${entry#*:}"
  user="oelite_${db}"
  pass="oelite_${db}_dev"

  echo "[$db] ($repo)"

  # Switch to the project DB and create a collection marker (ensures DB exists)
  MONGO_PROJECT_DB="$db" MONGO_PROJECT_USER="$user" MONGO_PROJECT_PASS="$pass" \
    mongosh -u "$ADMIN_USER" -p "$ADMIN_PASS" $mongosh_auth_base --eval '
    db = db.getSiblingDB(process.env.MONGO_PROJECT_DB);
    try { db.createCollection("_init_marker"); } catch (e) { if (!/already exists/i.test(e.message)) throw e; }
  ' >/dev/null 2>&1

  # Create the per-project user (scoped to the project DB only)
  MONGO_PROJECT_DB="$db" MONGO_PROJECT_USER="$user" MONGO_PROJECT_PASS="$pass" \
    mongosh -u "$ADMIN_USER" -p "$ADMIN_PASS" $mongosh_auth_base --eval '
    db = db.getSiblingDB(process.env.MONGO_PROJECT_DB);
    try {
      db.createUser({
        user: process.env.MONGO_PROJECT_USER,
        pwd: process.env.MONGO_PROJECT_PASS,
        roles: [{ role: "readWrite", db: process.env.MONGO_PROJECT_DB }]
      });
      print("  user created: " + process.env.MONGO_PROJECT_USER);
    } catch (e) {
      if (e.code === 51024 || /already exists/i.test(e.message)) {
        print("  user exists: " + process.env.MONGO_PROJECT_USER);
      } else {
        throw e;
      }
    }
  ' 2>/dev/null

  echo "  -> mongodb://$user:$pass@$MONGO_HOST:$MONGO_PORT/$db?authSource=$db"
  echo ""
done

echo "============================================================"
echo "  Per-project databases ready."
echo "============================================================"
echo ""
echo "Use these connection strings in your app's appsettings.init.json:"
echo ""
for entry in "${PROJECTS[@]}"; do
  db="${entry%%:*}"
  user="oelite_${db}"
  pass="oelite_${db}_dev"
  echo "  $db: mongodb://$user:$pass@localhost:27017/$db?authSource=$db"
done
echo ""
